// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBofxNmcbV_OdbIeslHzsYo6-tE6xGBUcg',
    appId: '1:52372297376:android:ab982dd1f8ce1165b75bc5',
    messagingSenderId: '52372297376',
    projectId: 'moneygement-c444e',
    storageBucket: 'moneygement-c444e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFfcy6ixzjIGPYUFCDiinSFV_oi9dUAVY',
    appId: '1:52372297376:ios:996d13195e383196b75bc5',
    messagingSenderId: '52372297376',
    projectId: 'moneygement-c444e',
    storageBucket: 'moneygement-c444e.firebasestorage.app',
    androidClientId: '52372297376-cqq81j4510ggupq6608hflosqfkj5a4v.apps.googleusercontent.com',
    iosClientId: '52372297376-fcpt31b7mv6q1a9tm7o2rgv8223f3548.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubesPmKelompok1',
  );

}